### ISSUE TITLE
报错Unable to connect to manager

### ISSUE THREAD

**Issue by yhyzzm** [Xuoos/StarRailProxy#3]
我使用lspatch用本地模式修补了SR2.2.53cn beta，并且勾上了模块作用域，但是进游戏提示这个并闪退
![Screenshot_2024-05-26-15-12-06-146_com miui home](https://github.com/Xuoos/StarRailProxy/assets/139681923/0e13ab40-68a7-42b7-aa13-431c69a86856)

**Comment by Xuoos** [comment]
> 我使用lspatch用本地模式修补了SR2.2.53cn beta，并且勾上了模块作用域，但是进游戏提示这个并闪退
> ![Screenshot_2024-05-26-15-12-06-146_com miui home](https://github.com/Xuoos/StarRailProxy/assets/139681923/0e13ab40-68a7-42b7-aa13-431c69a86856)
> 

cn包有检测，只能用lsp框架，lspatch不行

**Comment by yhyzzm** [comment]
lsp框架能做内置包嘛（我没root只能用lspatch
